New Top Token List
jup-ag/dynamic-slippage-config pull request #14
Opened 2024-11-29 03:12 UTC by boxme

# Problem
We have an existing list `dynamic_slippage_config.json` for dynamic slippage config setup based on token categories. We want to combine it with top token list.

To avoid disrupting anything related to prod, we don't want to modify the existing `dynamic_slippage_config.json`.

# Solution
A new updated list `top_tokens_config.json`. The changes also addition and removal of tokens from @0xSoju2 suggestions https://github.com/jup-ag/jupiter-core-rs/pull/1594/files

2024-11-29 03:59 UTC, Arrowana approved these changes
Other list has test to avoid adding wrong stuff / making corrupted json

2024-11-29 04:27 UTC, melvinzhang commented
Update CI to also run sanity check on this list.

2024-11-29 04:28 UTC, melvinzhang requested changes
Update CI to also do some sanity check on this list.

2024-11-29 06:30 UTC, boxme commented
> Update CI to also do some sanity check on this list.

Yeap, will do.

I won't be matching this PR for now because I can fetch this list off this branch and it's good enough for now.

2025-01-03 02:08 UTC, melvinzhang commented
Did not plan to close this but looks like auto closed when I merged https://github.com/jup-ag/dynamic-slippage-config/pull/17

DO NOT DELETE as we are reading a file from this branch for Quote API.

2025-01-13 11:38 UTC, melvinzhang commented
@boxme Have we deployed the Quote API that no longer depend on this branch?

2025-02-11 03:09 UTC, closed without merging